#===============connection===========================#
#srcdb.User = mine
#srcdb.Pwd = mine
#srcdb.Url = jdbc:mysql://192.168.106.17:8066/TESTDB?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
#srcdb.driver = com.mysql.jdbc.Driver
#srcdb.dbType= storeone
#srcdb.recordTable=STOREONEMIGRATION

#lengthTimes = 1

# ---- vb/pg/ivory-----
#resultdb.User =tdr
#resultdb.Pwd =tdr
##resultdb.Url = jdbc:postgresql://192.168.104.41:5432/ivorysql
#resultdb.Url = jdbc:postgresql://192.168.11.112:5432/pg
#resultdb.driver = org.postgresql.Driver
##resultdb.dbType = vastbase
#resultdb.recordTable=STOREONEMIGRATION


#---kingbase---#
#resultdb.dbType = kingbase
resultdb.User = mycat
resultdb.Pwd = mycat
resultdb.driver = com.kingbase8.Driver
resultdb.Url = jdbc:kingbase8://10.17.57.168:54321/test
#==== ivory/pg?????2? ????????1?
query.type=6
MaxThread=2
#storeOneTableSpace=TBS_TDR